### ISSUE TITLE
Redmine4.0にてmigrateが成功しない

### ISSUE THREAD

**Issue by nqdior** [ayapapa/redmine_backlogs#24]
コードお借りしております。
docker-compose 上のRedmine4.0にてインストール失敗しており、調査中です。
お知恵をお貸しください。

## 0. 環境情報
image ... Redmine:4.0
使用しているdocker-compose定義：https://blog1.mammb.com/entry/2020/05/24/090000

## 1. bundle install時にエラー発生 ①
```
root@d3efe946aa6d:/usr/src/redmine# bundle exec rake redmine:plugins:migrate RAILS_ENV=production

[!] There was an error parsing `Gemfile`:
[!] There was an error parsing `Gemfile`: You cannot specify the same gem twice with different version requirements.
You specified: nokogiri (~> 1.10.0) and nokogiri (>= 1.6.7.2). Bundler cannot continue.

 #  from /usr/src/redmine/plugins/redmine_backlogs/Gemfile:11
 #  -------------------------------------------
 #  gem "icalendar"
 >  gem "nokogiri", ">= 1.6.7.2"
 #  gem "open-uri-cached"
 #  -------------------------------------------
. Bundler cannot continue.

 #  from /usr/src/redmine/Gemfile:102
 #  -------------------------------------------
 #  Dir.glob File.expand_path("../plugins/*/{Gemfile,PluginGemfile}", __FILE__) do |file|
 >    eval_gemfile file
 #  end
 #  -------------------------------------------
```
　GemFile中の nokogiri, capybaraをコメントアウトしたところ、エラーメッセージが変わる（②へ）。

## 2. bundle install時にエラー発生 ②

```
Installing sidekiq 6.2.1
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /usr/local/bundle/gems/eventmachine-1.2.7/ext
/usr/local/bin/ruby -I /usr/local/lib/ruby/2.6.0 -r ./siteconf20210514-46-nbdmyz.rb extconf.rb
checking for -lcrypto... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=/usr/local/bin/$(RUBY_BASE_NAME)
        --with-ssl-dir
        --without-ssl-dir
        --with-ssl-include
        --without-ssl-include=${ssl-dir}/include
        --with-ssl-lib
        --without-ssl-lib=${ssl-dir}/lib
        --with-openssl-config
        --without-openssl-config
        --with-pkg-config
        --without-pkg-config
        --with-cryptolib
        --without-cryptolib
/usr/local/lib/ruby/2.6.0/mkmf.rb:467:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
        from /usr/local/lib/ruby/2.6.0/mkmf.rb:552:in `try_link0'
        from /usr/local/lib/ruby/2.6.0/mkmf.rb:570:in `try_link'
        from /usr/local/lib/ruby/2.6.0/mkmf.rb:789:in `try_func'
        from /usr/local/lib/ruby/2.6.0/mkmf.rb:1016:in `block in have_library'
        from /usr/local/lib/ruby/2.6.0/mkmf.rb:959:in `block in checking_for'
        from /usr/local/lib/ruby/2.6.0/mkmf.rb:361:in `block (2 levels) in postpone'
        from /usr/local/lib/ruby/2.6.0/mkmf.rb:331:in `open'
        from /usr/local/lib/ruby/2.6.0/mkmf.rb:361:in `block in postpone'
        from /usr/local/lib/ruby/2.6.0/mkmf.rb:331:in `open'
        from /usr/local/lib/ruby/2.6.0/mkmf.rb:357:in `postpone'
        from /usr/local/lib/ruby/2.6.0/mkmf.rb:958:in `checking_for'
        from /usr/local/lib/ruby/2.6.0/mkmf.rb:1011:in `have_library'
        from extconf.rb:8:in `block in check_libs'
        from extconf.rb:8:in `all?'
        from extconf.rb:8:in `check_libs'
        from extconf.rb:95:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /usr/local/bundle/extensions/x86_64-linux/2.6.0/eventmachine-1.2.7/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /usr/local/bundle/gems/eventmachine-1.2.7 for inspection.
Results logged to /usr/local/bundle/extensions/x86_64-linux/2.6.0/eventmachine-1.2.7/gem_make.out

An error occurred while installing eventmachine (1.2.7), and Bundler cannot continue.
Make sure that `gem install eventmachine -v '1.2.7' --source 'https://rubygems.org/'` succeeds before bundling.

In Gemfile:
  thin was resolved to 1.8.0, which depends on
    eventmachine


Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /usr/local/bundle/gems/json-2.5.1/ext/json/ext/generator
/usr/local/bin/ruby -I /usr/local/lib/ruby/2.6.0 -r ./siteconf20210514-46-ulw4ex.rb extconf.rb
creating Makefile

current directory: /usr/local/bundle/gems/json-2.5.1/ext/json/ext/generator
make "DESTDIR=" clean
sh: 1: make: not found

current directory: /usr/local/bundle/gems/json-2.5.1/ext/json/ext/generator
make "DESTDIR="
sh: 1: make: not found

make failed, exit code 127

Gem files will remain installed in /usr/local/bundle/gems/json-2.5.1 for inspection.
Results logged to /usr/local/bundle/extensions/x86_64-linux/2.6.0/json-2.5.1/gem_make.out

An error occurred while installing json (2.5.1), and Bundler cannot continue.
Make sure that `gem install json -v '2.5.1' --source 'https://rubygems.org/'` succeeds before bundling.

In Gemfile:
  json
```

★対策
    1. aptにてmake, gcc, g++をインストール。
    2. gem install eventmachine -v '1.2.7' --source 'https://rubygems.org/'
    3. gem install json -v '2.5.1

## 3. bundle exec 時にエラー発生

```
root@d3efe946aa6d:/usr/src/redmine# bundle install
The dependency tzinfo-data (>= 0) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby but the dependency is only for x86-mingw32, x64-mingw32, x86-mswin32. To add those platforms to the bundle, run `bundle lock --add-platform x86-mingw32 x64-mingw32 x86-mswin32`.
Fetching gem metadata from https://rubygems.org/............
Fetching gem metadata from https://rubygems.org/.
Resolving dependencies...
Using rake 13.0.3
~~~
Installing json 2.5.1 with native extensions
Installing eventmachine 1.2.7 with native extensions
Fetching thin 1.8.0
Installing thin 1.8.0 with native extensions
Bundle complete! 54 Gemfile dependencies, 78 gems now installed.
Gems in the groups development and test were not installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
root@d3efe946aa6d:/usr/src/redmine# bundle exec rake redmine:plugins:migrate RAILS_ENV=production
W, [2021-05-14T11:40:59.464614 #978]  WARN -- : Creating scope :system. Overwriting existing method Enumeration.system.
W, [2021-05-14T11:40:59.545109 #978]  WARN -- : Creating scope :backlog_scope. Overwriting existing method RbStory.backlog_scope.
W, [2021-05-14T11:40:59.562921 #978]  WARN -- : Creating scope :sorted. Overwriting existing method Group.sorted.
W, [2021-05-14T11:40:59.568963 #978]  WARN -- : Creating scope :sorted. Overwriting existing method User.sorted.
E, [2021-05-14T11:40:59.696230 #978] ERROR -- : Backlogs printable cards: problem loading labels: No such file or directory @ rb_sysopen - /usr/src/redmine/plugins/redmine_backlogs/lib/labels/labels.yaml
E, [2021-05-14T11:40:59.696392 #978] ERROR -- : /usr/local/lib/ruby/2.6.0/psych.rb:577:in `initialize'
~~~
I, [2021-05-14T11:41:00.097274 #978]  INFO -- : Migrating to RbAddHistory (38)
== 38 RbAddHistory: migrating =================================================
Rebuilding history...
     1 (     1/770)...
rake aborted!
StandardError: An error has occurred, all later migrations canceled:

undefined method `id' for 7:Integer
Did you mean?  i
/usr/src/redmine/plugins/redmine_backlogs/app/models/rb_issue_history.rb:35:in `block in statuses'
/usr/src/redmine/plugins/redmine_backlogs/app/models/rb_issue_history.rb:150:in `block (3 levels) in rebuild_issue'
/usr/src/redmine/plugins/redmine_backlogs/app/models/rb_issue_history.rb:149:in `each'
/usr/src/redmine/plugins/redmine_backlogs/app/models/rb_issue_history.rb:149:in `each_with_index'
/usr/src/redmine/plugins/redmine_backlogs/app/models/rb_issue_history.rb:149:in `block (2 levels) in rebuild_issue'
/usr/local/bundle/gems/activerecord-5.2.5/lib/active_record/relation/delegation.rb:71:in `each'
/usr/local/bundle/gems/activerecord-5.2.5/lib/active_record/relation/delegation.rb:71:in `each'
/usr/src/redmine/plugins/redmine_backlogs/app/models/rb_issue_history.rb:133:in `block in rebuild_issue'
/usr/local/bundle/gems/activerecord-5.2.5/lib/active_record/relation/delegation.rb:71:in `each'
/usr/local/bundle/gems/activerecord-5.2.5/lib/active_record/relation/delegation.rb:71:in `each'
/usr/src/redmine/plugins/redmine_backlogs/app/models/rb_issue_history.rb:129:in `rebuild_issue'
/usr/src/redmine/plugins/redmine_backlogs/app/models/rb_issue_history.rb:329:in `block in rebuild'
/usr/local/bundle/gems/activerecord-5.2.5/lib/active_record/relation/delegation.rb:71:in `each'
/usr/local/bundle/gems/activerecord-5.2.5/lib/active_record/relation/delegation.rb:71:in `each'
/usr/src/redmine/plugins/redmine_backlogs/app/models/rb_issue_history.rb:327:in `each_with_index'
/usr/src/redmine/plugins/redmine_backlogs/app/models/rb_issue_history.rb:327:in `rebuild'
/usr/src/redmine/plugins/redmine_backlogs/db/migrate/038_rb_add_history.rb:35:in `up'
```

Ruby側のバージョン問題と思われるが、原因特定できず。調査断念。

**Comment by ayapapa** [comment]
@nqdior さん、

「3. bundle exec 時にエラー発生」の、「undefined method `id' for 7:Integer」というエラーは、記憶では未経験ですが、コード(rb_issue_history.rb)を見ると、以下の部分が謎です。
```
        s = IssueStatus.first.id   ※ここでidをsに代入
        puts "IssueStatus #{k.inspect} not found, using default #{s.id} instead"  ※ここで、s(id)の.idメソッドを呼び出し？？（謎）
```
ここの部分は、前後の関係から、以下が正しいように思います。
```
        s = IssueStatus.first   ※ここで最初のIssueStatusをsに代入
        puts "IssueStatus #{k.inspect} not found, using default #{s.id} instead"  ※ここでs(ステータス)の.idメソッドを呼び出し
```
自分はruby2.5でのインストールは成功しておりますので、rubyのversionアップにより、エラーチェックが厳しくなったのかもしれません。いずれにせよ、明日以降になりますが、調べてみます。時間かかるかもしれませんが、悪しからず。

**Comment by ayapapa** [comment]
@nqdior さん、
本日を時間が出来たので、自分も再現させようとしましたが、同じエラーにはならず、対処することで無事インストールが成功しました。以下、その時の手順を記載しておきます。
違いがあるのは、rubyのバージョンですかね。自分の場合は、2.7になっていました。（railsのバージョンも違うかもしれません）。以下、自分が行った手順です。参考になれば幸いです。
ちなみに、利用したホストOSはUbuntu20.04です。

1. https://blog1.mammb.com/entry/2020/05/24/090000
に従い、docker-compose.ymlを作成
※ただし、自分のdocker-composeが古いためか、エラーになるので、`version: '3.8'`を'version: '3.3'`に書き換えた
2. sudo docker-compose up -d
3. curl localhost:3000
  -> 成功
4. sudo docker exec -it redmine bash
で、コンテナに突入。以下、コンテナ内で実行。
5. cd plugins
7. git clone https://github.com/ayapapa/redmine_backlog.git
8. git checkout redmine4
で、redmine ver.4 対応版に切り替え
9. ruby -v
で、念のためruby-バージョン確認したら、以下の通り2.7でした。
`ruby 2.7.3p183 (2021-04-05 revision 6847ee089d) [x86_64-linux]`
10. bundle install
 -> error
11. plugins/redmine_backlogs/Gemfile
にて、nokogiriをコメントアウト。※nokogiriのコメントアウトのみで大丈夫でした。
12. apt install make gcc g++
13. bundle install
 -> 成功
14. bundle exec rake redmine:plugins:migrate RAILS_ENV=production
 -> 途中エラーだが、アボートされずに終了
15. ブラウザにて、backlogsプラグインが導入されていることを目視で確認。

**Comment by nqdior** [comment]
@ayapapa さん
ご確認ありがとうございます。
こちらご教示頂いた方法（rb_issue_history.rb）で進めたところ、無事インストールできました。

以下、共有となります。
再起動後にブラウザで画面を確認していると、Backlogsを有効化したプロジェクトのチケット一覧タブを開くとInternal errorが表示されてしまいました。production.logの内容は以下の通りです。

```
I, [2021-06-02T15:47:32.048883 #1]  INFO -- : Completed 304 Not Modified in 9ms (ActiveRecord: 2.9ms)
I, [2021-06-02T15:47:33.588786 #1]  INFO -- : Started GET "/projects/aw_sp/issues" for 172.20.0.1 at 2021-06-02 15:47:33 +0000
I, [2021-06-02T15:47:33.590227 #1]  INFO -- : Processing by IssuesController#index as HTML
I, [2021-06-02T15:47:33.591045 #1]  INFO -- :   Parameters: {"project_id"=>"aw_sp"}
I, [2021-06-02T15:47:33.595398 #1]  INFO -- :   Current user: [user_name](id=5)
I, [2021-06-02T15:47:33.633265 #1]  INFO -- :   Rendering issues/index.html.erb within layouts/base
I, [2021-06-02T15:47:33.707116 #1]  INFO -- :   Rendered queries/_filters.html.erb (71.4ms)
I, [2021-06-02T15:47:33.707559 #1]  INFO -- :   Rendered queries/_query_form.html.erb (72.0ms)
I, [2021-06-02T15:47:33.707844 #1]  INFO -- :   Rendered issues/index.html.erb within layouts/base (73.9ms)
I, [2021-06-02T15:47:33.708264 #1]  INFO -- : Completed 500 Internal Server Error in 117ms (ActiveRecord: 18.8ms)
F, [2021-06-02T15:47:33.709031 #1] FATAL -- :   
F, [2021-06-02T15:47:33.709379 #1] FATAL -- : ActionView::Template::Error (undefined method `remote' for #<Hash:0x0000556a9e46b168>):
F, [2021-06-02T15:47:33.709666 #1] FATAL -- :     1: <%= javascript_tag do %>
    2: var operatorLabels = <%= raw_json Query.operators_labels %>;
    3: var operatorByType = <%= raw_json Query.operators_by_filter_type %>;
    4: var availableFilters = <%= raw_json query.available_filters_as_json %>;
    5: var labelDayPlural = <%= raw_json l(:label_day_plural) %>;
    6: 
    7: var filtersUrl = <%= raw_json queries_filter_path(:project_id => @query.project.try(:id), :type => @query.type) %>;
F, [2021-06-02T15:47:33.709988 #1] FATAL -- :   
F, [2021-06-02T15:47:33.710306 #1] FATAL -- : app/models/query.rb:499:in `block in available_filters_as_json'
app/models/query.rb:497:in `each'
app/models/query.rb:497:in `available_filters_as_json'
app/views/queries/_filters.html.erb:4:in `block in _app_views_queries__filters_html_erb___1349548542336755797_46958198431500'
app/views/queries/_filters.html.erb:1:in `_app_views_queries__filters_html_erb___1349548542336755797_46958198431500'
app/views/queries/_query_form.html.erb:10:in `_app_views_queries__query_form_html_erb___4431419030027823514_46958198333140'
app/views/issues/index.html.erb:24:in `block in _app_views_issues_index_html_erb___516296191174028305_46958198185400'
app/views/issues/index.html.erb:23:in `_app_views_issues_index_html_erb___516296191174028305_46958198185400'
app/controllers/issues_controller.rb:54:in `block (2 levels) in index'
app/controllers/issues_controller.rb:49:in `index'
lib/redmine/sudo_mode.rb:65:in `sudo_mode'
```

つきまして、以下URLの通りソースコードを修正したところ、解決できました。
https://blog.adachin.me/archives/6343

素晴らしい改修をありがとうございます。
これからプロジェクトの基幹として利用させて頂きます。

引き続きよろしくお願い致します。

**Comment by ayapapa** [comment]
@nqdior さん、

情報共有ありがとうございます。
internal errorの件調査したところ、以前redmine 3.4対応で取り込んだ修正が、redmine4では有効になっていなかったことが分かりました。(実は、自分もredmine4対応時にこのことを失念しており、redmine4本体側にパッチをあてて利用するようにしていた記憶がよみがえりました。。。）

ということで、本件、このプラグイン（issue #25）において正式に修正を加える予定です。

また、何かありましたら、連絡ください。
